// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Beverage.
const (
	Cider Beverage = "cider"
	Mead  Beverage = "mead"
	Wine  Beverage = "wine"
)

// Valid indicates whether the value is a known member of the Beverage enum.
func (e Beverage) Valid() bool {
	switch e {
	case Cider:
		return true
	case Mead:
		return true
	case Wine:
		return true
	default:
		return false
	}
}

// Defines values for IngredientCategory.
const (
	IngredientCategoryChemical    IngredientCategory = "chemical"
	IngredientCategoryFermentable IngredientCategory = "fermentable"
	IngredientCategoryFruit       IngredientCategory = "fruit"
	IngredientCategoryNutrient    IngredientCategory = "nutrient"
	IngredientCategoryOther       IngredientCategory = "other"
	IngredientCategoryYeast       IngredientCategory = "yeast"
)

// Valid indicates whether the value is a known member of the IngredientCategory enum.
func (e IngredientCategory) Valid() bool {
	switch e {
	case IngredientCategoryChemical:
		return true
	case IngredientCategoryFermentable:
		return true
	case IngredientCategoryFruit:
		return true
	case IngredientCategoryNutrient:
		return true
	case IngredientCategoryOther:
		return true
	case IngredientCategoryYeast:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin  UserRole = "admin"
	Member UserRole = "member"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}

// Defines values for VesselKind.
const (
	VesselKindBarrel VesselKind = "barrel"
	VesselKindBucket VesselKind = "bucket"
	VesselKindCarboy VesselKind = "carboy"
	VesselKindKeg    VesselKind = "keg"
	VesselKindOther  VesselKind = "other"
	VesselKindTank   VesselKind = "tank"
)

// Valid indicates whether the value is a known member of the VesselKind enum.
func (e VesselKind) Valid() bool {
	switch e {
	case VesselKindBarrel:
		return true
	case VesselKindBucket:
		return true
	case VesselKindCarboy:
		return true
	case VesselKindKeg:
		return true
	case VesselKindOther:
		return true
	case VesselKindTank:
		return true
	default:
		return false
	}
}

// Beverage defines model for Beverage.
type Beverage string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Ingredient defines model for Ingredient.
type Ingredient struct {
	Category IngredientCategory `json:"category"`
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Unit     string             `json:"unit"`
}

// IngredientCategory defines model for IngredientCategory.
type IngredientCategory string

// IngredientInput defines model for IngredientInput.
type IngredientInput struct {
	Category IngredientCategory `json:"category"`
	Name     string             `json:"name"`
	Unit     string             `json:"unit"`
}

// InventoryRow defines model for InventoryRow.
type InventoryRow struct {
	CostPerUnit *float32   `json:"costPerUnit,omitempty"`
	Ingredient  Ingredient `json:"ingredient"`
	Stock       float32    `json:"stock"`
}

// Invite defines model for Invite.
type Invite struct {
	CreatedAt     time.Time          `json:"createdAt"`
	CreatedBy     openapi_types.UUID `json:"createdBy"`
	CreatedByName string             `json:"createdByName"`
	Email         *string            `json:"email,omitempty"`
	ExpiresAt     time.Time          `json:"expiresAt"`
	Id            openapi_types.UUID `json:"id"`
	RevokedAt     *time.Time         `json:"revokedAt,omitempty"`
	Token         string             `json:"token"`
	UsedAt        *time.Time         `json:"usedAt,omitempty"`
	UsedByName    *string            `json:"usedByName,omitempty"`
}

// InviteCreate defines model for InviteCreate.
type InviteCreate struct {
	Email *string `json:"email,omitempty"`
}

// InvitePreview defines model for InvitePreview.
type InvitePreview struct {
	Email *string `json:"email,omitempty"`
	Valid bool    `json:"valid"`
}

// Occupant defines model for Occupant.
type Occupant struct {
	BatchId   openapi_types.UUID `json:"batchId"`
	BatchName string             `json:"batchName"`
	Beverage  Beverage           `json:"beverage"`
	Since     openapi_types.Date `json:"since"`
	VolumeL   float32            `json:"volumeL"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Status int     `json:"status"`
	Title  string  `json:"title"`
	Type   string  `json:"type"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email       string `json:"email"`
	InviteToken string `json:"inviteToken"`
	Name        string `json:"name"`
	Password    string `json:"password"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// StockAdjust defines model for StockAdjust.
type StockAdjust struct {
	Delta float32 `json:"delta"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Role      UserRole           `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// Vessel defines model for Vessel.
type Vessel struct {
	CapacityL float32            `json:"capacityL"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Kind      VesselKind         `json:"kind"`
	Name      string             `json:"name"`
	Notes     *string            `json:"notes,omitempty"`
	Occupant  *Occupant          `json:"occupant,omitempty"`
}

// VesselInput defines model for VesselInput.
type VesselInput struct {
	CapacityL float32    `json:"capacityL"`
	Kind      VesselKind `json:"kind"`
	Name      string     `json:"name"`
	Notes     *string    `json:"notes,omitempty"`
}

// VesselKind defines model for VesselKind.
type VesselKind string

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = Credentials

// AuthChangePasswordJSONRequestBody defines body for AuthChangePassword for application/json ContentType.
type AuthChangePasswordJSONRequestBody = ChangePasswordRequest

// AuthRegisterJSONRequestBody defines body for AuthRegister for application/json ContentType.
type AuthRegisterJSONRequestBody = RegisterRequest

// AuthSetupJSONRequestBody defines body for AuthSetup for application/json ContentType.
type AuthSetupJSONRequestBody = SetupRequest

// CreateIngredientJSONRequestBody defines body for CreateIngredient for application/json ContentType.
type CreateIngredientJSONRequestBody = IngredientInput

// AdjustStockJSONRequestBody defines body for AdjustStock for application/json ContentType.
type AdjustStockJSONRequestBody = StockAdjust

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = InviteCreate

// CreateVesselJSONRequestBody defines body for CreateVessel for application/json ContentType.
type CreateVesselJSONRequestBody = VesselInput

// UpdateVesselJSONRequestBody defines body for UpdateVessel for application/json ContentType.
type UpdateVesselJSONRequestBody = VesselInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	AuthLogin(w http.ResponseWriter, r *http.Request)

	// (POST /auth/logout)
	AuthLogout(w http.ResponseWriter, r *http.Request)

	// (GET /auth/me)
	AuthMe(w http.ResponseWriter, r *http.Request)

	// (POST /auth/password)
	AuthChangePassword(w http.ResponseWriter, r *http.Request)

	// (POST /auth/register)
	AuthRegister(w http.ResponseWriter, r *http.Request)

	// (POST /auth/setup)
	AuthSetup(w http.ResponseWriter, r *http.Request)

	// (GET /auth/status)
	AuthStatus(w http.ResponseWriter, r *http.Request)

	// (POST /ingredients)
	CreateIngredient(w http.ResponseWriter, r *http.Request)

	// (GET /inventory)
	ListInventory(w http.ResponseWriter, r *http.Request)

	// (POST /inventory/{ingredientId}/adjust)
	AdjustStock(w http.ResponseWriter, r *http.Request, ingredientId openapi_types.UUID)

	// (GET /invites)
	ListInvites(w http.ResponseWriter, r *http.Request)

	// (POST /invites)
	CreateInvite(w http.ResponseWriter, r *http.Request)

	// (GET /invites/preview/{token})
	PreviewInvite(w http.ResponseWriter, r *http.Request, token string)

	// (POST /invites/{id}/revoke)
	RevokeInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /members)
	ListMembers(w http.ResponseWriter, r *http.Request)

	// (GET /vessels)
	ListVessels(w http.ResponseWriter, r *http.Request)

	// (POST /vessels)
	CreateVessel(w http.ResponseWriter, r *http.Request)

	// (DELETE /vessels/{id})
	DeleteVessel(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PUT /vessels/{id})
	UpdateVessel(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/login)
func (_ Unimplemented) AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/logout)
func (_ Unimplemented) AuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/me)
func (_ Unimplemented) AuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/password)
func (_ Unimplemented) AuthChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/register)
func (_ Unimplemented) AuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/setup)
func (_ Unimplemented) AuthSetup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /auth/status)
func (_ Unimplemented) AuthStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ingredients)
func (_ Unimplemented) CreateIngredient(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /inventory)
func (_ Unimplemented) ListInventory(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /inventory/{ingredientId}/adjust)
func (_ Unimplemented) AdjustStock(w http.ResponseWriter, r *http.Request, ingredientId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /invites)
func (_ Unimplemented) ListInvites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /invites)
func (_ Unimplemented) CreateInvite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /invites/preview/{token})
func (_ Unimplemented) PreviewInvite(w http.ResponseWriter, r *http.Request, token string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /invites/{id}/revoke)
func (_ Unimplemented) RevokeInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /members)
func (_ Unimplemented) ListMembers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /vessels)
func (_ Unimplemented) ListVessels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /vessels)
func (_ Unimplemented) CreateVessel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /vessels/{id})
func (_ Unimplemented) DeleteVessel(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /vessels/{id})
func (_ Unimplemented) UpdateVessel(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) AuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthMe operation middleware
func (siw *ServerInterfaceWrapper) AuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthChangePassword operation middleware
func (siw *ServerInterfaceWrapper) AuthChangePassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthRegister operation middleware
func (siw *ServerInterfaceWrapper) AuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthSetup operation middleware
func (siw *ServerInterfaceWrapper) AuthSetup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthSetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthStatus operation middleware
func (siw *ServerInterfaceWrapper) AuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIngredient operation middleware
func (siw *ServerInterfaceWrapper) CreateIngredient(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIngredient(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInventory operation middleware
func (siw *ServerInterfaceWrapper) ListInventory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInventory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdjustStock operation middleware
func (siw *ServerInterfaceWrapper) AdjustStock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "ingredientId" -------------
	var ingredientId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ingredientId", chi.URLParam(r, "ingredientId"), &ingredientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ingredientId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdjustStock(w, r, ingredientId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInvites operation middleware
func (siw *ServerInterfaceWrapper) ListInvites(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInvites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateInvite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewInvite operation middleware
func (siw *ServerInterfaceWrapper) PreviewInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", chi.URLParam(r, "token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewInvite(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeInvite operation middleware
func (siw *ServerInterfaceWrapper) RevokeInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeInvite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMembers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVessels operation middleware
func (siw *ServerInterfaceWrapper) ListVessels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVessels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVessel operation middleware
func (siw *ServerInterfaceWrapper) CreateVessel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVessel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVessel operation middleware
func (siw *ServerInterfaceWrapper) DeleteVessel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVessel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVessel operation middleware
func (siw *ServerInterfaceWrapper) UpdateVessel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVessel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/setup", wrapper.AuthSetup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.AuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.AuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.AuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password", wrapper.AuthChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/status", wrapper.AuthStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/invites", wrapper.ListInvites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/invites", wrapper.CreateInvite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/invites/{id}/revoke", wrapper.RevokeInvite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/invites/preview/{token}", wrapper.PreviewInvite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/members", wrapper.ListMembers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vessels", wrapper.ListVessels)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vessels", wrapper.CreateVessel)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vessels/{id}", wrapper.DeleteVessel)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vessels/{id}", wrapper.UpdateVessel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ingredients", wrapper.CreateIngredient)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/inventory", wrapper.ListInventory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/inventory/{ingredientId}/adjust", wrapper.AdjustStock)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFnNcts2EH4VDtpbWUlOcqlujtuDx07isZv04NF0IHIlISIBBljK0Xj47h0ApAiKIEU5lpqTKXKx2P3w",
	"7Q/WzyQSaSY4cFRk+kwkqExwBebHnRTzBFL9GAmOwFE/0ixLWESRCT7OrMRvX5Xg+puKVpBS/fSrhAWZ",
	"kl/Gtf6x/arGld6iKEISg4oky7Q6MiV/SSkk0e9LYa3rPWxA0iXoZ+B5SqaP5IlxICFJgcYkJBGLQZJZ",
	"SHCbAZkShZLxJSlCcrWifAl3VKknIeN7+JaDMm5kUmQgkVlXo1xK4FjJ6VctVRye3O8p47fAl7gi04tJ",
	"a+ciJBK+5UxCrM3d19/UVhsu5l8hQmO4hBg4MpqotrmQUpZ4jcy6PdgzyepwVvisuOZLCTGrjj5JPi3I",
	"9LH/eOs11zzLtZp985kxbyFkSpFMSZ4zjUi/ucxn4Kxh4hVFWAq5dXmyAJkCRzpPNF0WMmdIQrIFqvRf",
	"nqM0zoVEG88iqhERuOpg075rbR45JgzDaGe0ZhhNYZ9aHityzvCg2B58RnVY21dq8Z/5BjgKub0XTx4P",
	"hcI7kJ9LG8rVPE/nIPVq1mDMMAz0OoUiWns07tOgXlSt6fCBIXisl0AR4ktsEDCmCL8jMwi10C6XvN8O",
	"4Kwj/bE8y5ZEd+zC94xJUMcYNyiSNIIbsT7ObRRr4F4zc3WcJi3fiUc7yqutXeT3cQ2dg3Rx66bClZEf",
	"nkmLTk13EjYMno5JyhuaMDcjz4VIgPKW91bO58SnKMozyj0ZZ04xWl0Po4GR7STm3CmzfXG7K8c6ahmP",
	"oEUF394bkeQp3B6O8Moh11zHuFpTtbsPL6d1acIVA3adkkKKuXI+MY6wtFkNGSZ+1OyLQ7w2Xys1u618",
	"lt/DkikE6bQqw8ruA2CeVas8NdeQ9++OqG5l2VrYX3Ubux0RCgNLXPbSRqvqasp619vcPOjycRl/zX0u",
	"xJAgPcxWK+bT/lmBfJUC1A3mwOzPuyJeiqTRVNM4Zdx01cbXWTgkW+8hbnS6+dmHzRdQCpLh3LbyXe3k",
	"CzAdiJxw0m6ffbv07EWoD4vZDo3OjjKjEcOtyZzwPUpyxTbwgXGW6kOrA6JuwdaMx4cstnveaMnhUckF",
	"gjqcPUomGDNCx4FuJtyUFldEjKicC13253m0BjS1QErQNEPK11o5LHs6dZ3NIcolw+2DdrgK6Q2z1cqg",
	"YCoxUAmyPvoVYmZqASjF7J2W6XtpJMSaQcXyKYnW/1Yiu7U0YzewtbdaxhfCbunebu+kiPNI/whQ0mgN",
	"MlgIGazEfL5lCgN9qQ0DfacNA8rjwFxrg5SuQarRrnxMyRUkCZU3AFlweXetSyJIay65GE1GE0PdDDjN",
	"GJmSt6OL0cTkQlwZHMY0x9U4EUtmHMyEzX+adeZar7sJcpnj6taI2MMFhe9FvO0ZBhw3BHDvt0WTQShz",
	"MC+cWcSbyeTVtjaZ2TN8+HSjgXs3edulYGeRM8KomUamjzP9ewevKOO5D18t03L1XZs6t2K5hDjQ4kVR",
	"72LDdgkdG3wA8j/ieHEMjrVPbu3vxq452DkVSb3To0F09Zyh1RaPgsskCcr0oQLGTduvK8SogYMsO8F+",
	"HKp+8UQI7Lejg3y/ODnF7HXO1K53b968Rrwq3dD2Q2163hPh3Ozefz6QJ3+8Csi7K1ZnynqwIj+Ytpo9",
	"FAeI1UN1wAcu4Y5wu2Fpg/TPCnQTEhj+BCuqAplzPwT17Ep1E82Cfu2OuU7Bt9aQ9ryUc2d/PcQrStzK",
	"gWQncW6Zwt3Y8ke5wxBSddgBZ0haD4uolHTbVRP3vBk/14S4josxrW+i/hRkvptLq+nmJE0BQSpzezJd",
	"qu7w6h7V1U72Dzd0HD40iJ+dKOU51+8TdIDNFDBwvNw1UW4f6Ed4Cox0kMAGEud0WXlJ6mOqkTkTTxnC",
	"cIaGB9KS0XaqlOQMaouSESfLPxaWIblHn9U4s1Pf8bMZThed51tOh3dAHQ7TatrdHZ/eeDxRT9+ccXfR",
	"xFvcLFDPLC7G9v8N3ans3nw/AiT2ChnspIj153w7UOvPCh9KmXNkBdvxHVO1NmZO0+/Bl1LmHB6UE8Sh",
	"PjQI+1yPdx5nRVgPhh5nZh7XlwHLfU+TARtjzvM2ZBWeBxNiSQQT5+WcHOw/1ppw/WneO3Aduh3bBS+5",
	"bRTnySDleLbp5ucs/ulYMTkDK8rM0BdYM/1NbqozyWVCpmRMMzbeXJBiVvwXAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
